In [1]:
import numpy as np

In [11]:
# Exemplo do Introduction to Probability Theory na página 188

m = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

print(np.dot(m, m))
print(np.linalg.matrix_power(m, 2))

print(np.linalg.matrix_power(m, 4))

[[0.61 0.39]
 [0.52 0.48]]
[[0.61 0.39]
 [0.52 0.48]]
[[0.5749 0.4251]
 [0.5668 0.4332]]


In [29]:
# Exercicio 1

m = np.array([
    [0.7, 0.2, 0.1],
    [0.0, 0.6, 0.4],
    [0.5, 0.0, 0.5]
])

print(np.linalg.matrix_power(m, 2))

[[0.54 0.26 0.2 ]
 [0.2  0.36 0.44]
 [0.6  0.1  0.3 ]]


In [17]:
# Exercicio 4 

m = np.array([
    [0, 1/2, 1/2],
    [1/2, 0, 1/2],
    [1/2, 1/2, 0]
])

print(np.linalg.matrix_power(m, 4))

[[0.375  0.3125 0.3125]
 [0.3125 0.375  0.3125]
 [0.3125 0.3125 0.375 ]]


In [28]:
# Exercicio 5

m = np.array([
    [0.3, 0.2, 0.5],
    [0.5, 0.1, 0.4],
    [0.5, 0.2, 0.3]
])

print(np.linalg.matrix_power(m, 2))
print(0.44 * 0.5 + 0.4 * 0.5)

print(np.linalg.matrix_power(m, 3))
print(0.412 * 0.5 + 0.42 * 0.5)

[[0.44 0.18 0.38]
 [0.4  0.19 0.41]
 [0.4  0.18 0.42]]
0.42000000000000004
[[0.412 0.182 0.406]
 [0.42  0.181 0.399]
 [0.42  0.182 0.398]]
0.416


In [31]:
# Exercicio 6

m = np.array([
    [0.3, 0.7],
    [0.8, 0.2]
])

print(np.linalg.matrix_power(m, 3))
print(0.525 * 0.5 + 0.4 * 0.5)

[[0.475 0.525]
 [0.6   0.4  ]]
0.4625
