In [2]:
import numpy as np

In [6]:
# Exercicio 9

m = np.array([
    [0.95, 0.05],
    [0.2, 0.8]
])

print(np.linalg.matrix_power(m, 8))

[[0.82002258 0.17997742]
 [0.71990967 0.28009033]]


In [8]:
# Prova 1

p = 0.5
q = 0.5

m = np.array([
    [0, 1, 0, 0, 0, 0],
    [p, 0, 1-p, 0, 0, 0],
    [0, p, 0, 1-p, 0, 0],
    [0, 0, p, 0, 1-p, 0],
    [0, 0, 0, p, 0, 1-p],
    [0, 0, 0, 0, 1 ,0]
])

print(np.linalg.matrix_power(m, 1))
print(np.linalg.matrix_power(m, 2))
print(np.linalg.matrix_power(m, 3))
print(np.linalg.matrix_power(m, 4))
print(np.linalg.matrix_power(m, 5))
print(np.linalg.matrix_power(m, 6))

[[0.  1.  0.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.  1.  0. ]]
[[0.5  0.   0.5  0.   0.   0.  ]
 [0.   0.75 0.   0.25 0.   0.  ]
 [0.25 0.   0.5  0.   0.25 0.  ]
 [0.   0.25 0.   0.5  0.   0.25]
 [0.   0.   0.25 0.   0.75 0.  ]
 [0.   0.   0.   0.5  0.   0.5 ]]
[[0.    0.75  0.    0.25  0.    0.   ]
 [0.375 0.    0.5   0.    0.125 0.   ]
 [0.    0.5   0.    0.375 0.    0.125]
 [0.125 0.    0.375 0.    0.5   0.   ]
 [0.    0.125 0.    0.5   0.    0.375]
 [0.    0.    0.25  0.    0.75  0.   ]]
[[0.375  0.     0.5    0.     0.125  0.    ]
 [0.     0.625  0.     0.3125 0.     0.0625]
 [0.25   0.     0.4375 0.     0.3125 0.    ]
 [0.     0.3125 0.     0.4375 0.     0.25  ]
 [0.0625 0.     0.3125 0.     0.625  0.    ]
 [0.     0.125  0.     0.5    0.     0.375 ]]
[[0.      0.625   0.      0.3125  0.      0.0625 ]
 [0.3125  0.      0.46875 0.      0.21875 0.     ]
 [0.      0.46875 0.      0.37