Condição de existência da decomposição LU para uma matriz A  
<img src="menores_principais.png" alt="Drawing" style="height: 400px; width: 550px;"/>  
Exemplo:  
<img src="menores_principais_exemplo.png" alt="Drawing" style="height: 300px; width: 450px;"/>  

<img src="decomposicao_lu.png" alt="Drawing" style="height: 400px; width: 550px;"/> 

In [2]:
# Codificando a Decomposicao LU
import numpy as np
def decomposicao_lu(A):
    # A: matriz quadrada
    # L, U: matrizes triangular inferior e superior, respectivamente
    n = np.shape(A)[0]
    L = np.eye(n)
    U = np.zeros((n, n))
    for k in np.arange(n):
        for j in np.arange(k, n):
            U[k,j]=A[k,j]
            for s in np.arange(k):
                U[k, j] = U[k,j] - L[k, s]*U[s, j]
            for i in np.arange(k+1, n):
                L[i, k] = A[i, k]
                for s in np.arange(k):
                    L[i,k] = L[i, k] - L[i, s] * U[s, k]
                L[i, k] = L[i, k]/U[k, k]
    return L, U

A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]])
L, U = decomposicao_lu(A)
print(L)
print (U)

# Utilizando a Decomposicao LU do sympy
import sympy
A = sympy.Matrix([[1, 2, 0], [1, 3, 1], [-2, 0, 1]])
L, U, _ = A.LUdecomposition()
print(L)
print(U)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  4.  1.]]
[[ 1.  2.  0.]
 [ 0.  1.  1.]
 [ 0.  0. -3.]]
Matrix([[1, 0, 0], [1, 1, 0], [-2, 4, 1]])
Matrix([[1, 2, 0], [0, 1, 1], [0, 0, -3]])
