In [ ]:
import numpy as np
from scipy import linalg as lin
import math as m
import matplotlib.pyplot as plt

# Potência
def potencia(A,tol):
    k = 0; kmax = 10000; erro = np.inf;
    n = np.shape(A)[0]; y0 = np.zeros(n); y0[0] = 1;

    while(erro > tol and k < kmax):
        x = A.dot(y0);
        y = x/np.linalg.norm(x);
        erro = np.abs(np.abs(y0.dot(y))-1);
        y0 = y; k = k+1;
    
    lambda_ = y.dot(A.dot(y));
    return lambda_, y, k

#Potência Inversa
def potencia_inv(A,tol):
    k = 0; kmax = 10000; erro = np.inf;
    n = np.shape(A)[0]; y0 = np.zeros(n); y0[0] = 1;

    while(erro > tol and k < kmax):
        x = np.linalg.solve(A,y0);
        y = x/np.linalg.norm(x);
        erro = np.abs(np.abs(y0.dot(y))-1);
        y0 = y; k = k+1;

    lambda_ = y.dot(A.dot(y));
    return lambda_, y, k

# Exemplo
A = np.array([[-4, 14, 0],  
              [ -5, 13, 0],
              [ -1, 0,2]], dtype='double')
print(A);

(D_python,V_python) = np.linalg.eig(A); # usando uma função pronta para calcular todos os autovalores

print('Cálculo do maior autovalor em módulo de A')
(lambda_,y,k) = potencia(A,0.000001)
print('Potência: %.4f  usando %d iterações' %(lambda_,k))
print('Python: %.4f\n' %(np.max(abs(D_python))))

# input('\n');

print('Cálculo do menor autovalor em módulo de A')
(lambda_inv,y,k) = potencia_inv(A,0.000001)
print('Potência Inversa: %.4f  usando %d iterações' %(lambda_inv,k))
print('Python: %.4f\n' %(np.min(abs(D_python))))

[[-4. 14.  0.]
 [-5. 13.  0.]
 [-1.  0.  2.]]
Cálculo do maior autovalor em módulo de A
Potência: 6.0043  usando 10 iterações
Python: 6.0000

Cálculo do menor autovalor em módulo de A
Potência Inversa: 1.9982  usando 16 iterações
Python: 2.0000

