In [2]:
import numpy as np
import math as m

import numpy as np
import math as m

# QR 
def clgsQR(A):
    (m,n) = np.shape(A);
    Q = np.zeros((m,n));
    R = np.zeros((n,n));

    for j in np.arange(n):
        V = A[:,j];
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(A[:,j]); 
            V = V - R[i,j]*Q[:,i];
        R[j,j] = np.linalg.norm(V);
        Q[:,j] = V/R[j,j];

    return Q,R

# QR modificado
def mgsQR(A):
    (m,n) = np.shape(A);
    V = np.copy(A); 
    Q = np.zeros((m,n));
    R = np.zeros((n,n));

    for j in np.arange(n):
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(V[:,j]); 
            V[:,j] = V[:,j] - R[i,j]*Q[:,i];
        R[j,j] = np.linalg.norm(V[:,j]);
        Q[:,j] = V[:,j]/R[j,j];

    return Q,R

# Exemplo
B = np.array([[1, 1, 0],  
              [0, 1, 2],  
              [1, 0, 1],
              [0, 1, 3]], dtype='double')
print(B)
(m,n) = np.shape(B);

print('Calculando decomposição QR clássica\n')
(Q_c,R_c) = clgsQR(B);
print(Q_c); print(R_c);

print('Calculando o erro da decomposição QR clássica')
B_calc = Q_c.dot(R_c); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

input("\n")

print('Calculando decomposição QR modificada\n')
(Q_c,R_c) = mgsQR(B);
print(Q_c); print(R_c);

print('Calculando o erro da decomposição QR modificada')
B_calc = Q_c.dot(R_c); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

# Francis
def francis(A,tol,flag):
    if flag == 'classico':
        print('QR',flag,'\n')
        qr = clgsQR;
    if flag == 'modificado':
        print('QR',flag,'\n')
        qr = mgsQR;
    if flag == 'python':
        print('QR',flag,'\n')
        qr = np.linalg.qr;
    
    n = np.shape(A)[0];
    A_local = np.copy(A);
    V = np.eye(n);
    erro = np.inf

    while erro > tol:
        [Q,R] = qr(A_local);
        A_local = R.dot(Q);
        V = V.dot(Q);

        erro = np.max(np.max(np.abs(np.tril(A_local,-1))));
    
    D = np.diag(A_local);

    return D,V

input("\n")

# Exemplo
C = np.transpose(B).dot(B);
print(C)
n_c = np.shape(C)[0];

print('Calculando autovalores com método de Francis\n')

tol = 0.000001; flag = 'python';
(D,V) = francis(C,tol,flag);

print(V);
print(D);

print('\nChecando a ortogonalidade de V')

I_c = np.transpose(V).dot(V);
I = np.eye(n_c);
norm_I_c = np.linalg.norm(I-I_c,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I_c))

[[1. 1. 0.]
 [0. 1. 2.]
 [1. 0. 1.]
 [0. 1. 3.]]
Calculando decomposição QR clássica

[[ 0.70710678  0.31622777 -0.60246408]
 [ 0.          0.63245553  0.0860663 ]
 [ 0.70710678 -0.31622777  0.60246408]
 [ 0.          0.63245553  0.51639778]]
[[1.41421356 0.70710678 0.70710678]
 [0.         1.58113883 2.84604989]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR clássica
O erro da decomposição é: 7.58e-17

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 4.09e-16



Calculando decomposição QR modificada

[[ 0.70710678  0.31622777 -0.60246408]
 [ 0.          0.63245553  0.0860663 ]
 [ 0.70710678 -0.31622777  0.60246408]
 [ 0.          0.63245553  0.51639778]]
[[1.41421356 0.70710678 0.70710678]
 [0.         1.58113883 2.84604989]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR modificada
O erro da decomposição é: 7.58e-17

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 4.09e-16



[[ 2.  1.  1.]
 [ 1.  3. 