<img src="estrategia_pivoteamento_parcial.png" alt="Drawing" style="height: 400px; width: 550px;"/>   
Depois de permutar, basta realizar a Eliminação de Gauss até encontrar a necessidade do pivoteamento parcial novamente (se houver) e repetir os passos

In [2]:
# Neste exemplo estamos fazendo o pivotemaento em todo caso, não só quando um elemento < E 

import numpy as np

def eliminacao_gauss_pivoteamento_parcial(A, b):
    n = np.shape(A)[0]
    newA = np.copy(A)
    newb = np.copy(b)
    
    for k in np.arange(n-1):
        # Realizando o Pivoteamento Parcial
        p = np.argmax(np.abs(newA[k:n, k]))
        newA[[k, p], k:n] = newA[[p,k], k:n]
        newb[[k,p]] = newb[[p, k]]
        
        # Eliminacao de Gauss sem o Pivoteamento Parcial
        for i in np.arange(k+1, n):
            m = -newA[i, k]/newA[k,k]
            newA[i, k:n] = newA[i, k:n] + m*newA[k, k:n]
            newb[i] = newb[i] + m*newb[k]
    
    return newA, newb

A = np.array([
    [1, 1, 1],
    [1, 0, 10],
    [0, 10, 1]], dtype='double'
)
b = [0, -48, 25]

newA, newb = eliminacao_gauss_pivoteamento_parcial(A, b)
print(newA, newb)

[[ 1.  1.  1.]
 [ 0. -1.  9.]
 [ 0.  0. 91.]] [   0  -48 -455]
