<img src="eliminacao_gauss.png" alt="Drawing" style="height: 400px; width: 550px;"/> 

In [1]:
import numpy as np
def eliminacao_gauss(A, b):
    # Ax=b
    # Retorna A'x=b' equivalente a Ax=b
    n = len(b)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if A[i, k] != 0.0:
                lam = A[i, k]/A[k,k]
                A[i, k+1:n] = A[i, k+1:n] - lam*A[k, k+1:n]
                b[i] = b[i] - lam*b[k]
    return A, b

A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]])
b = np.array([3, 5, -1])
U, b = eliminacao_gauss(A, b)
print(U)
print(b)

[[ 1  2  0]
 [ 1  1  1]
 [-2  4 -3]]
[ 3  2 -3]


Observação: 
"A matriz U que sai do código Eliminação de Gauss é diferente da U do código de Decomposição LU. Eu implementei no Eliminação de Gauss de forma que altera a U apenas nos índices que tenho interesse, então repare nos elementos da diagonal e acima dela, daí fará sentido. Isso não dá problema porque utilizo a substituição regressiva e os elementos que eram para resultar em 0 não interferem."  
- Código LU: [{1,2,0},{0,1,1},{0,0,-3}]
- Eliminação de Gauss: [{1,2,0},{1(diferente e não interfere),  1,1},{-2(diferente e não interfere), 0(diferente e não interfere),  -3}] 